DROP TABLE IF EXISTS usermusic;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS musictypes;
DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS roles;
CREATE TABLE IF NOT EXISTS roles (
  id SERIAL PRIMARY KEY UNIQUE,
  name VARCHAR(30) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS addresses (
  id SERIAL PRIMARY KEY UNIQUE,
  address VARCHAR(250) NOT NULL UNIQUE
);
CREATE TABLE  IF NOT EXISTS musictypes (
  id SERIAL PRIMARY KEY UNIQUE,
  type VARCHAR(30) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY UNIQUE,
  login VARCHAR(30) NOT NULL UNIQUE,
  address INTEGER REFERENCES addresses(id) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS usermusic (
  id SERIAL PRIMARY KEY UNIQUE,
  user_id INTEGER REFERENCES users(id) NOT NULL,
  musictype INTEGER REFERENCES musictypes(id) NOT NULL
);