# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Ветки
branches:
  only:
  - master
  - development

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE \"job4j-test\";" -U postgres
  - psql -c "CREATE DATABASE webtest_test;" -U postgres

notifications:
  email:
    recipients:
      - bujhtitxrf@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
